spring:
  profiles:
    active: local
    group:
      test: common-test
      local: common-local
      dev: common-dev
      prod: common-prod

decorator:
  datasource:
    exclude-beans: dataSource, routingDataSource

Logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
