spring:
  config:
    activate:
      on-profile: common-local
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tester
    password: wkaqh12Q!

  servlet:
    multipart:
      max-file-size: 25GB
      max-request-size: 25GB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false
  cloud:
    openfeign:
      lazy-attributes-resolution: true