spring:
  application:
    name: workout-backend
  jpa:
    show-sql: false
    properties:
      hibernate:
        use_sql_comments: true
  jackson:
    time-zone: UTC
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    com.workout: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

upload:
  local:
    dir: ${UPLOAD_DIR:./uploads/}

fcm:
  service-account-key-path: "classpath:config/fcm-key.json"