spring:
  application:
    name: workout-backend
  jpa:
    show-sql: false
    properties:
      hibernate:
        use_sql_comments: true
  jackson:
    time-zone: UTC
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: omori235@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
  batch:
    job:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    com.workout: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

upload:
  local:
    dir: ${UPLOAD_DIR:./uploads/}

fcm:
  service-account-key-path: "classpath:config/fcm-key.json"