# application-docker.yml (이 내용을 전체 복사하여 붙여넣으세요)

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/workout-db?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
  jpa:
    hibernate:
      ddl-auto: validate
  session:
    store-type: redis
  data:
    redis:
      host: redis
      port: 6379
  flyway:
    locations: classpath:/migration
  batch:
    job:
      enabled: false
  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: my-workout-api
    distribution:
      slo:
        "[http.server.requests]": 1ms, 5ms, 10ms, 50ms, 100ms, 500ms, 1s, 5s, 10s
      percentiles-histogram:
        "[http.server.requests]": true

encryption:
  key: ${ENCRYPTION_KEY}

default:
  profile:
    image:
      url: ${DEFAULT_PROFILE_IMAGE_URL}

  circuitbreaker:
    instances:
      redis-circuit:
        register-health-indicator: true
        failure-rate-threshold: 60
        sliding-window-type: COUNT_BASED
        sliding-window-size: 50
        minimum-number-of-calls: 20
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 5

springdoc:
  swagger-ui:
    url: /v3/api-docs

fcm:
  service-account-key-path: "file:/app/config/fcm-key.json"