spring:
  application:
    name: workout-backend
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: UTC
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: omori235@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

upload:
  local:
    dir: ${UPLOAD_DIR:./uploads/}

