spring:
  application:
    name: workout-backend
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: UTC
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

upload:
  local:
    dir: ${UPLOAD_DIR:./uploads/}

