# application-docker.yml
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/workout-db?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME} # 실제 값은 .env 파일에서 주입
    password: ${DB_PASSWORD} # 실제 값은 .env 파일에서 주입
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  session:
    store-type: redis
  data:
    redis:
      host: redis
      port: 6379