spring:
  application:
    name: workout-backend
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: UTC
  flyway:
    enabled: true

upload:
  local:
    dir: ${UPLOAD_DIR:./uploads/}